version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8080"
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  