# Use the .NET SDK image for development
FROM mcr.microsoft.com/dotnet/sdk:7.0

# Set the working directory inside the container
WORKDIR /app

# Copy csproj and restore any dependencies (via NuGet)
COPY *.csproj ./
RUN dotnet restore

EXPOSE 8080

# Set the entry point to use dotnet watch
ENTRYPOINT ["dotnet", "watch", "run", "--urls=http://+:8080/"]
