CREATE TABLE zglossip."CUISINE"
(
    "RECIPE_ID" integer NOT NULL,
    "TEXT" character varying(10) COLLATE NOT NULL,
    CONSTRAINT "CUISINE_pkey" PRIMARY KEY ("RECIPE_ID", "TEXT"),
    CONSTRAINT "RECIPE_FK" FOREIGN KEY ("RECIPE_ID")
        REFERENCES zglossip."RECIPE" ("ID") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)