CREATE TABLE zglossip."INSTRUCTION"
(
    "RECIPE_ID" integer NOT NULL,
    "TEXT" character varying(500) NOT NULL,
    "POSITION" integer NOT NULL,
    CONSTRAINT "INSTRUCTION_pkey" PRIMARY KEY ("RECIPE_ID", "TEXT"),
    CONSTRAINT "RECIPE_FK" FOREIGN KEY ("RECIPE_ID")
        REFERENCES zglossip."RECIPE" ("ID") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)